name: Trigger Lambda via Webhook

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 11 * * *' # Runs every day at 12:00 UTC

jobs:
  trigger-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to API Gateway
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"instance_ids":["i-0b76fa72ccda9bdae","i-0ffa983bd0e4faff5"]}' \
          https://u6wvf7447f.execute-api.us-east-1.amazonaws.com/shutdown
